### ISSUE TITLE
Improve DashboardController and its SemanticComponentInterface

### ISSUE THREAD

**Issue by cpr-fer** [CommonplaceRobotics/iRC_ROS#35]
The current implementation does what it is supposed to do, but is still far from being good

TODOs:
- [x] Pass that vector to the SCI (#36)
- [x] Make sure all state interfaces are handled  (#36)
- [ ] Once controller_type is a state interface implement it as well (#48)
- [x] Reorder methods in dashboard controller file (#36)
- [ ] Test with TUI Dashboard

**Comment by cpr-fer** [comment]
I removed "Read in the list of states to listen to from the .ros2_control.urdf into a vector" from the TODOs, as I am not sure that dynamically reading only a subset of the states could have any advantages, especially considering the extra LoC in the controller configuration
